#!/usr/bin/env bash
# mechanical-leads.sh — deterministic mechanical-lead scans for a pinned CL.
#
# Usage: mechanical-leads.sh <parent-sha> <revision-sha> [worktree-dir]
#
# Run inside (or point at) the pinned review worktree. Markdown is written to
# stdout; save it as <review-dir>/mechanical-leads.md.
#
# Every hit below is a ledger candidate: the Mechanical Leads thread copies
# each into ledger/ML.md with a row ID and either explains it clean (with a
# path:line citation) or leaves it as a candidate for verification.
#
# This script covers only the deterministic scans. The manual leads in
# references/discovery-checklists.md "Mechanical Leads" — visiting the
# callers of changed functions, reading feature-flag polarity, the
# guard-bypass scan, direct-include checks, and coverage-tool flags — remain
# the thread's job (see the checklist reminder at the bottom of the output).

set -u
export LC_ALL=C

PARENT="${1:?usage: mechanical-leads.sh <parent-sha> <revision-sha> [worktree-dir]}"
REV="${2:?usage: mechanical-leads.sh <parent-sha> <revision-sha> [worktree-dir]}"
REPO="${3:-$(pwd)}"

G() { git -C "$REPO" "$@"; }

G rev-parse --git-dir >/dev/null 2>&1 || { echo "ERROR: $REPO is not a git checkout" >&2; exit 1; }
G cat-file -e "$PARENT^{commit}" 2>/dev/null || { echo "ERROR: parent $PARENT not found in $REPO" >&2; exit 1; }
G cat-file -e "$REV^{commit}" 2>/dev/null || { echo "ERROR: revision $REV not found in $REPO" >&2; exit 1; }

# --- helpers ---------------------------------------------------------------

# Added lines of the diff as "file:line:content" (line numbers in the new
# file). Args: pathspecs.
added_lines() {
  G diff --color=never --unified=0 "$PARENT" "$REV" -- "$@" 2>/dev/null | awk '
    /^\+\+\+ / {
      file = $0
      sub(/^\+\+\+ b\//, "", file)
      sub(/^\+\+\+ /, "", file)
      next
    }
    /^@@/ {
      match($0, /\+[0-9]+/)
      line = substr($0, RSTART + 1, RLENGTH - 1) + 0
      n = 0
      next
    }
    /^\+/ {
      printf "%s:%d:%s\n", file, line + n, substr($0, 2)
      n++
      next
    }
  '
}

# Print stdin as capped bullet rows; announce the cap instead of hiding it.
emit_capped() {
  local cap="$1"
  local buf total
  buf="$(cat)"
  if [[ -z "$buf" ]]; then
    echo "(no hits)"
    return
  fi
  total=$(printf '%s\n' "$buf" | wc -l)
  printf '%s\n' "$buf" | head -n "$cap" | sed 's/^/- `/; s/$/`/'
  if (( total > cap )); then
    printf -- '- … and %d more hits (CAPPED — note this cap in the ML rows; do not treat the list as complete)\n' $((total - cap))
  fi
}

section() { printf '\n## %s\n\n' "$1"; }

# Pick a scanner for the one PCRE-ish pattern (non-ASCII).
NONASCII_CMD=""
if command -v rg >/dev/null 2>&1; then
  NONASCII_CMD="rg [^[:ascii:]]"
elif printf 'x' | grep -qP 'x' 2>/dev/null; then
  NONASCII_CMD="grep -P [^\x00-\x7F]"
fi

ADDED_CC="$(mktemp)"
ADDED_ALL="$(mktemp)"
trap 'rm -f "$ADDED_CC" "$ADDED_ALL"' EXIT
added_lines '*.cc' '*.h' '*.mm' > "$ADDED_CC"
added_lines '*.cc' '*.h' '*.mm' '*.md' > "$ADDED_ALL"

# --- output ----------------------------------------------------------------

cat <<EOF
# Mechanical leads — $PARENT..$REV

Generated by scripts/mechanical-leads.sh. Every hit is a ledger candidate:
copy each into ledger/ML.md with a row ID (ML-1, ML-2, ...) and either
explain it clean with a \`path:line\` citation or leave it as a candidate
for verification. A capped list is an incomplete list — say so in the rows.
EOF

section "Changed files (per-file ledger floor input)"
G diff --name-status "$PARENT" "$REV" | sed 's/^/- `/; s/$/`/'

section "Whitespace and conflict markers (git diff --check)"
CHECK_OUT="$(G diff --check "$PARENT" "$REV" 2>&1 || true)"
if [[ -n "$CHECK_OUT" ]]; then
  printf '%s\n' "$CHECK_OUT" | emit_capped 40
else
  echo "(clean)"
fi

section "Formatter diff (git clang-format)"
HEAD_NOW="$(G rev-parse HEAD 2>/dev/null || true)"
if [[ "$HEAD_NOW" != "$REV" ]]; then
  echo "SKIPPED: worktree HEAD is not the pinned revision — run inside the pinned worktree. Record as unrun in Verification Notes."
elif ! G clang-format -h >/dev/null 2>&1; then
  echo "UNAVAILABLE: git clang-format not found (depot_tools not on PATH?). Record as unrun in Verification Notes."
else
  CF_ARGS=()
  for c in "$REPO/buildtools/linux64/clang-format" \
           "$REPO/buildtools/mac/clang-format" \
           "$REPO/buildtools/mac_arm64/clang-format"; do
    if [[ -x "$c" ]]; then CF_ARGS=(--binary "$c"); break; fi
  done
  CF_OUT="$(G clang-format ${CF_ARGS[@]+"${CF_ARGS[@]}"} --diff "$PARENT" 2>&1 || true)"
  if [[ -z "$CF_OUT" ]] || printf '%s' "$CF_OUT" | grep -qiE 'no modified files|did not modify'; then
    echo "(clean — note: clang-format neither adds nor removes blank lines; scan those manually in the polish pass)"
  else
    echo '```diff'
    printf '%s\n' "$CF_OUT" | head -n 120
    echo '```'
  fi
fi

section "Non-ASCII characters in added lines (.cc/.h/.mm/.md)"
if [[ -n "$NONASCII_CMD" ]]; then
  # shellcheck disable=SC2086
  $NONASCII_CMD < "$ADDED_ALL" 2>/dev/null | emit_capped 30
else
  echo "UNAVAILABLE: neither rg nor grep -P present. Run the checklist's non-ASCII scan manually."
fi

section "Added bool declarations (predicate-name check: is_/has_/should_/did_/can_/needs_...)"
grep -E '(^|[^A-Za-z0-9_])bool[[:space:]]+[A-Za-z0-9_]+_[[:space:]]*[;={]' "$ADDED_CC" | emit_capped 25

section "Count-returning calls with possibly discarded results (Push/Pull/Write/Send/Read)"
echo "Partial acceptance is the contract for these APIs; verify each result is consumed."
echo
grep -E '^[^:]*:[0-9]+:[[:space:]]*([A-Za-z0-9_]+(\.|->))*(Push|Write|Send|Pull|Read)[A-Za-z0-9_]*\(' "$ADDED_CC" \
  | grep -vE '=|return|if[[:space:]]*\(|while[[:space:]]*\(|for[[:space:]]*\(|EXPECT_|ASSERT_|DCHECK|CHECK\(|<<' \
  | emit_capped 25

section "Callback/task/lifetime tokens in added lines"
echo "For each: name the object that owns the callback target and the line guaranteeing the callback cannot outlive it."
echo
grep -E 'PostTask|PostDelayedTask|BindOnce|BindRepeating|base::Unretained|OneShotTimer|RepeatingTimer|RetainingOneShotTimer|DeadlineTimer' "$ADDED_CC" | emit_capped 30

section "Named sentinels in added lines (definitions listed side by side)"
SENTINELS="$(grep -oE 'k(Unlimited|Invalid|No[A-Z]|None|Null|Max|Min|Infinite)[A-Za-z0-9_]*' "$ADDED_CC" | sort -u | head -10)"
if [[ -z "$SENTINELS" ]]; then
  echo "(no hits)"
else
  echo "Two modules encoding the same concept with different values is a candidate by default."
  while IFS= read -r s; do
    printf '\n### `%s`\n\n' "$s"
    G grep -n -w "$s" -- '*.cc' '*.h' 2>/dev/null | emit_capped 12
  done <<< "$SENTINELS"
fi

section "Preprocessor gates in added lines (verify polarity vs feature name and default build)"
grep -E '^[^:]*:[0-9]+:[[:space:]]*#[[:space:]]*(if|ifdef|ifndef|elif)' "$ADDED_ALL" | emit_capped 20

section "Feature flags referenced in added lines (grep every gate site; check polarity and default agreement)"
FEATURES="$(grep -oE '(BASE_FEATURE\([[:space:]]*k[A-Za-z0-9_]+|features::k[A-Za-z0-9_]+)' "$ADDED_CC" \
  | grep -oE 'k[A-Za-z0-9_]+' | sort -u | head -10)"
if [[ -z "$FEATURES" ]]; then
  echo "(no hits)"
else
  while IFS= read -r f; do
    printf '\n### `%s`\n\n' "$f"
    G grep -n -w "$f" -- '*.cc' '*.h' '*.mm' '*.gn' '*.gni' 2>/dev/null | emit_capped 12
  done <<< "$FEATURES"
fi

section "Changed-function inventory (reference counts; visit non-test callers manually)"
echo "Changed semantics with unchanged callers is a classic miss. Counts are tree-wide git-grep line counts."
echo
FUNCS="$(G diff --color=never "$PARENT" "$REV" -- '*.cc' '*.h' '*.mm' 2>/dev/null \
  | grep -E '^@@' | sed -E 's/^@@[^@]*@@[[:space:]]*//' \
  | sed -E 's/\(.*$//; s/[[:space:]]+$//; s/.*[[:space:]:~*&]//' \
  | grep -E '^[A-Za-z_][A-Za-z0-9_]{3,}$' \
  | grep -vE '^(if|for|while|switch|else|return|namespace|class|struct|enum|TEST|TEST_F|TEST_P|public|private|protected|final|override|const)$' \
  | grep -vE '^[A-Z0-9_]+$' \
  | sort -u | head -20)"
if [[ -z "$FUNCS" ]]; then
  echo "(no enclosing functions detected in hunk headers)"
else
  while IFS= read -r fn; do
    CNT="$(G grep -n -E "(^|[^A-Za-z0-9_])$fn\(" -- '*.cc' '*.h' '*.mm' 2>/dev/null | wc -l)"
    printf -- '- `%s` — %s reference line(s) across the tree\n' "$fn" "$CNT"
  done <<< "$FUNCS"
  echo
  echo "(enclosing-function names parsed from hunk headers; capped at 20 — enumerate the rest from the diff if truncated)"
fi

section "Cross-component includes added (verify BUILD.gn deps)"
grep -E '^[^:]*:[0-9]+:[[:space:]]*#include "' "$ADDED_CC" | awk '
{
  line = $0
  file = line; sub(/:.*/, "", file)
  split(file, fp, "/"); ftop = fp[1]
  content = line; sub(/^[^:]*:[0-9]+:/, "", content)
  inc = content; sub(/^[[:space:]]*#include "/, "", inc); sub(/".*/, "", inc)
  if (inc !~ /\//) next
  split(inc, ip, "/"); itop = ip[1]
  if (itop != ftop && itop != "base" && itop != "build" && itop != "testing")
    printf "%s includes \"%s\" — verify the target'\''s BUILD.gn deps\n", file, inc
}' | emit_capped 20

section "Test-reference map (changed files vs '*test*' files that mention their stem)"
FILES="$(G diff --name-only "$PARENT" "$REV" -- '*.cc' '*.h' '*.mm' | grep -viE 'test|mock|fake' | head -40)"
if [[ -z "$FILES" ]]; then
  echo "(no non-test source files changed)"
else
  while IFS= read -r f; do
    stem="$(basename "$f")"; stem="${stem%.*}"
    HITS="$(G grep -l -F "$stem" -- '*test*' 2>/dev/null | head -3)"
    if [[ -z "$HITS" ]]; then
      printf -- '- `%s`: NO test file references `%s` — coverage candidate by default\n' "$f" "$stem"
    else
      printf -- '- `%s`: referenced by %s\n' "$f" "$(printf '%s' "$HITS" | tr '\n' ' ')"
    fi
  done <<< "$FILES"
fi

section "Manual leads still owed by the Mechanical Leads thread"
cat <<'EOF'
Not scriptable — execute per references/discovery-checklists.md "Mechanical
Leads" and record each as a row:

- Visit every non-test caller of each changed/new function (inventory above).
- For each feature flag/build gate: read every gate site for polarity and
  default agreement (sites listed above are leads, not answers).
- Guard-bypass scan: pre-existing statements newly wrapped in `if (!flag)`,
  new early returns/`continue`s above old logic, old branches short-circuited
  by new state.
- Direct-include check for new symbols (std::, base::, test helpers).
- Coverage-tooling flags on changed lines, if Gerrit shows them.
EOF
