#!/usr/bin/env python3

from __future__ import annotations

from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest

SCRIPTS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPTS))

import build_worker_references  # noqa: E402


SOURCE = """# Sample Reference

**Untrusted data rule.** Preamble contract that must travel with sections.

## Contents

- [First Rule](#first-rule)

## First Rule

**Rule stated in bold.** The rule text itself.

  A measured run failed this way once; this rationale block is skippable
  by the reference's own declaration.

- A list item.
  Its indented continuation is normative and must survive.

The lead-in below ends with a colon and introduces indented content:

  This indented block is introduced, not rationale, and must survive.

## Second Rule

```markdown
## Fenced Heading Must Not Split

  indented fenced content must survive
```

Closing text.
"""


class WorkerReferenceTests(unittest.TestCase):
    def setUp(self) -> None:
        self.root = Path(tempfile.mkdtemp(prefix="worker-refs-"))
        self.addCleanup(shutil.rmtree, self.root, True)
        (self.root / "sample.md").write_text(SOURCE, encoding="utf-8")

    def build(self) -> Path:
        build_worker_references.build(self.root)
        return self.root / "worker" / "sample"

    def test_split_sections_and_index(self) -> None:
        stem = self.build()
        names = sorted(path.name for path in stem.iterdir())
        self.assertEqual(
            names, ["first-rule.md", "index.md", "second-rule.md"])
        index = (stem / "index.md").read_text(encoding="utf-8")
        self.assertIn("first-rule.md", index)
        self.assertNotIn("contents", index.lower().replace(
            "table of contents", ""))

    def test_preamble_travels_with_every_section(self) -> None:
        stem = self.build()
        for name in ("first-rule.md", "second-rule.md"):
            text = (stem / name).read_text(encoding="utf-8")
            self.assertIn("Preamble contract", text)
            self.assertIn("Generated from", text)

    def test_rationale_stripped_normative_preserved(self) -> None:
        stem = self.build()
        first = (stem / "first-rule.md").read_text(encoding="utf-8")
        self.assertNotIn("A measured run failed", first)
        self.assertIn("The rule text itself.", first)
        self.assertIn("Its indented continuation is normative", first)
        self.assertIn("introduced, not rationale", first)

    def test_fenced_content_untouched(self) -> None:
        stem = self.build()
        second = (stem / "second-rule.md").read_text(encoding="utf-8")
        self.assertIn("## Fenced Heading Must Not Split", second)
        self.assertIn("indented fenced content must survive", second)
        self.assertFalse((stem / "fenced-heading-must-not-split.md").exists())

    def test_regeneration_is_clean_and_deterministic(self) -> None:
        stem = self.build()
        stale = stem / "stale.md"
        stale.write_text("stale", encoding="utf-8")
        before = (stem / "first-rule.md").read_bytes()
        self.build()
        self.assertFalse(stale.exists())
        self.assertEqual(before, (stem / "first-rule.md").read_bytes())

    def test_documented_worker_paths_exist(self) -> None:
        """Every references/worker/... path named in the skill docs must be
        generated by the builder — guards against slug typos in briefs."""
        import re

        skill = SCRIPTS.parent
        references = skill / "references"
        with tempfile.TemporaryDirectory(prefix="worker-doc-check-") as temp:
            staged = Path(temp) / "references"
            shutil.copytree(references, staged,
                            ignore=shutil.ignore_patterns("worker"))
            build_worker_references.build(staged)
            pattern = re.compile(
                r"references/worker/([A-Za-z0-9._/-]+\.md)")
            documented = set()
            for doc in [skill / "SKILL.md", *references.glob("*.md")]:
                documented.update(pattern.findall(
                    doc.read_text(encoding="utf-8")))
            self.assertTrue(documented, "no documented worker paths found")
            missing = sorted(
                path for path in documented
                if "⟨" not in path and not (staged / "worker" / path).is_file())
            self.assertEqual(missing, [])

    def test_stripped_blocks_match_golden(self) -> None:
        """The rationale-strip heuristic must remove exactly the blocks the
        golden fixture records for the real reference files. When a canonical
        reference gains or loses a rationale block intentionally, regenerate
        the fixture (instructions in its header); an unexpected diff here
        means the heuristic started eating normative text or leaking
        rationale."""
        references = SCRIPTS.parent / "references"
        observed = ["# Golden record of rationale blocks stripped from the",
                    "# canonical references by build_worker_references.py.",
                    "# Regenerate: python3 -m unittest "
                    "scripts.tests.test_worker_references (see assertion",
                    "# message for the observed value) or update by hand "
                    "when a rationale block is added/removed on purpose.",
                    ""]
        from collections import Counter

        for source in sorted(references.glob("*.md")):
            lines = source.read_text(encoding="utf-8").splitlines()
            stripped = build_worker_references.strip_rationale(lines)
            delta = Counter(lines) - Counter(stripped)
            for line in lines:
                if delta.get(line, 0) > 0 and line.strip():
                    delta[line] -= 1
                    observed.append(f"{source.name}: {line.strip()[:70]}")
        golden_path = Path(__file__).parent / "fixtures" / \
            "stripped-rationale-golden.txt"
        self.assertTrue(golden_path.is_file(),
                        f"missing golden fixture {golden_path}")
        golden = golden_path.read_text(encoding="utf-8").rstrip("\n")
        self.assertEqual(
            "\n".join(observed), golden,
            "stripped-block set changed; if intentional, update "
            f"{golden_path} to:\n" + "\n".join(observed))

    def test_cli_runs(self) -> None:
        result = subprocess.run(
            [sys.executable, str(SCRIPTS / "build_worker_references.py"),
             str(self.root)],
            capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("generated", result.stdout)


if __name__ == "__main__":
    unittest.main()
